feat: error fallback component
ShabadOS/theme-tool pull request #47
Opened 2020-06-15 19:51 UTC by saihaj

### Summary of PR
Modifies the desktop component and implements it here
![image](https://user-images.githubusercontent.com/44710980/84699650-80e7b980-af17-11ea-9eec-47ae4d6388a3.png)

### Tests for unexpected behavior
Forced it to break and then clearing it makes it work.

### Time spent on PR
1 hour

### Reviewers
@Harjot1Singh @bhajneet

2020-06-15 20:19 UTC, bhajneet commented
If it crashes with non-default local storage, can't it simply clear local
storage automatically to try and fix it?

On Mon, Jun 15, 2020 at 3:51 PM ਸਹਜਪ੍ਰੀਤ ਸਿੰਘ <notifications@github.com>
wrote:

> Summary of PR
>
> Modifies the desktop component and implements it here
> [image: image]
> <https://user-images.githubusercontent.com/44710980/84699650-80e7b980-af17-11ea-9eec-47ae4d6388a3.png>
> Tests for unexpected behavior
>
> Forced it to break and then clearing it makes it work.
> Time spent on PR
>
> 1 hour
> Reviewers
>
> @Harjot1Singh <https://github.com/Harjot1Singh> @bhajneet
> <https://github.com/bhajneet>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ShabadOS/theme-tool/pull/47
> Commit Summary
>
>    - feat: error fallback component
>
> File Changes
>
>    - *D* logo.png
>    <https://github.com/ShabadOS/theme-tool/pull/47/files#diff-1bb87d41d15fe27b500a4bfcde01bb0e>
>    (0)
>    - *M* src/App.js
>    <https://github.com/ShabadOS/theme-tool/pull/47/files#diff-14b1e33d5bf5649597cdc0e4f684dadd>
>    (3)
>    - *A* src/assets/images/logo.png
>    <https://github.com/ShabadOS/theme-tool/pull/47/files#diff-155edcbd976df0c3246554b12df78687>
>    (0)
>    - *A* src/components/ErrorFallback.css
>    <https://github.com/ShabadOS/theme-tool/pull/47/files#diff-ce210e263d14ee9d0da9dfe67cb4769b>
>    (71)
>    - *A* src/components/ErrorFallback.js
>    <https://github.com/ShabadOS/theme-tool/pull/47/files#diff-28eddce14fb45b8e6628bee8062944dd>
>    (106)
>
> Patch Links:
>
>    - https://github.com/ShabadOS/theme-tool/pull/47.patch
>    - https://github.com/ShabadOS/theme-tool/pull/47.diff
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ShabadOS/theme-tool/pull/47>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADLZ3B4GZHKMQZVPBNXI3LTRWZ3THANCNFSM4N6RMVTQ>
> .
>

2020-06-15 20:40 UTC, saihaj commented
> If it crashes with non-default local storage, can't it simply clear local storage automatically to try and fix it?
> […](#)

Most probably with non-default local storage it won't crash, unless someone forces changes. Right now it can only reset itself if you try to delete properties. 

This component is just as a safety measure so that if in future there are any breaking changes then the old version of app can sync up with new one instead of showing a blank screen.

2020-06-23 18:55 UTC, harjot1singh requested changes
I would suggest adding some margin from the top or similar.

2020-06-23 18:55 UTC, Harjot1Singh commented on src/components/ErrorFallback.css
> +  .error-fallback .error {
Your formatting is broke in this file. Please comb through it to check spacing is correct (2 per indent)

2020-06-23 18:55 UTC, Harjot1Singh commented on src/components/ErrorFallback.js
> +    if ( error ) {
newline

2020-06-23 18:55 UTC, Harjot1Singh commented on src/components/ErrorFallback.js
> +
extra newline

2020-06-23 18:55 UTC, Harjot1Singh commented on src/components/ErrorFallback.js
> +import './ErrorFallback.css'
The closest import goes at the end

2020-06-23 18:55 UTC, Harjot1Singh commented on src/components/ErrorFallback.css
> +}
Missing EOF newline

2020-06-23 19:13 UTC, saihaj commented
> I would suggest adding some margin from the top or similar.

Move down the popup ?

2020-06-24 16:03 UTC, harjot1singh approved these changes

2020-06-24 16:03 UTC, Harjot1Singh commented
> > I would suggest adding some margin from the top or similar.
> 
> Move down the popup ?

Yes

2020-06-24 16:05 UTC, harjot1singh requested changes
Move it down a tad

2020-06-28 14:28 UTC, harjot1singh approved these changes
All good.

I think in the future, we should start thinking about bundling up our own component library/UI presets etc.

2020-06-28 14:28 UTC, merged